### ISSUE TITLE
Implement Array.observe

### ISSUE THREAD

**Issue by MaxArt2501** [MaxArt2501/object-observe#10]
Based on [the spec](http://arv.github.io/ecmascript-object-observe/#Array.observe).

Basically, it's a matter to implement the detection of the `splice` event inside the dirty checking loop. `Array.unobserve` should behave just like `Object.unobserve`.

**Comment by tomalec** [comment]
:+1: Do you have any plan for this?

**Comment by MaxArt2501** [comment]
In fact, I do.
It's not a problem of detecting "splice" changes - a distance function (such as Levenshtein's) should do the trick - but a matter of implementation strategy. Detecting splices is a computationally hefty operation that should be done only for Array-like objects that are observed for `splice` changes. All of these tasks and checks have their computational cost.

I'd like to prioritize adding benchmarks (#11) before this one, and hopefully something should move as soon as I go on a break and have a little time for my projects.

**Comment by MaxArt2501** [comment]
In the meanwhile, I created a [separate polyfill](https://github.com/MaxArt2501/array-observe) for `Array.observe`.
