### ISSUE TITLE
Safari and Safari mobile support

### ISSUE THREAD

**Issue by kristfal** [MaxArt2501/object-observe#12]
Neither browsers are listed as supported. Implement a simple observe test, but it fails without any error messages on both platforms. Is there something wrong on my side, or doesn't this shim support those browsers?

**Comment by MaxArt2501** [comment]
Although I've never done extensive tests on those platforms, I haven't encountered any problem so far. I've just run the tests on Safari 8.0.7 and all passed. (I should add it to the readme.)

Anyway, I _did_ read about a problem on mobile Safari in the wild, but couldn't replicate. Can you provide the code of what you did exactly?

**Comment by kristfal** [comment]
Thanks for the quick reply, might be on my side then. Project in the wild with this issue can be found at:

https://github.com/olanod/mapbox-gl-map-element

Implementation works out of the box in Chrome and Opera. Shim works in Firefox (haven't tested IE), but fails in Safari and Safari mobile. Let me know if you need more info.

**Comment by MaxArt2501** [comment]
Thanks, I will look into it later.

**Comment by MaxArt2501** [comment]
I tried the demo in that project and everything suggests it's an issue independent by this polyfill.
In fact, for some reason `Object.observe` _doesn't even get called_ in Safari, so of course the markers' positions don't get updated.
In Chrome and Firefox the elements are correctly observed, with the latter using the polyfill without any problem.

The [tests](../blob/master/doc/index.md#tests) all pass in both Mac OS and iOS Safari, although on iOS I had to lengthen the `setTimeout` interval to perform the check (probably `requestAnimationFrame` can't quite achieve 60 fps there).

Not knowing the project there's a chance I've missed something, but for what I've seen I suggest opening an issue about making mapbox-gl-map-element work with Safari altogether.

I'll leave this issue open until everything is clear.
Alternatively, you can close it yourself.

**Comment by MaxArt2501** [comment]
Since nothing new emerged from this, I hope you don't mind if I close this issue.
