### ISSUE TITLE
compared to objserve-js?

### ISSUE THREAD

**Issue by stevenvachon** [MaxArt2501/object-observe#14]
https://github.com/polymer/observe-js

is not mentioned in https://github.com/MaxArt2501/object-observe/blob/master/doc/index.md

I'm curious how they differ.

**Comment by MaxArt2501** [comment]
Even if the goal of observing changes in objects' properties is the same, the interface is completely different.
This polyfill aims to be an exact replacement for `Object.observe`, and although it's not possible to perfectly achieve that, it's meant to make developers comfortable with the upcoming ES7 feature.

On the other hand, observe-js offers an interface which can take advantage of `Object.observe`, but if it's not present it provides a replacement that's sharply designed for the given interface.

I haven't really used observe-js, but I suggest using either that _or_ this polyfill, and not both, as this polyfill would replace the observer in observe-js, possibly with detrimental effects performance-wise.

**Comment by stevenvachon** [comment]
Are there strengths and weaknesses between the two? I like the idea of a polyfill, but I also prefer not to extend `Object`.

**Comment by MaxArt2501** [comment]
The main problem with extending native objects and classes is the risk of naming clash with upcoming standard features with custom ones, but when a module is _meant_ to polyfill an upcoming feature such problem simply doesn't exist.  (Also notice this polyfill does _not_ replace the enviroment's native implementation of `Object.observe`.)

You can see `Object.observe` as a "low-level" property mutation observer: it doesn't do deep or property path observation, for example. It's all up to you to implement those features for your needs.

**Comment by stevenvachon** [comment]
My gripe with shimming `Object.observe()` is more of a maintenance issue. Anything using it appears to be using the native function, while an `objectObserve()` is immediately obvious that it is not.

**Comment by MaxArt2501** [comment]
What's actually different if an `objectObserve` function uses `Object.observe` if it's available?

Polyfills work like this: they mimic native features so developers can immediately use them, at least partially, waiting for them to be supported by the environment.
I've clearly stated the main problems of this polyfill, so it's up to the developer to decide if they're acceptable.
