### ISSUE TITLE
make this a "ponyfill"

### ISSUE THREAD

**Issue by stevenvachon** [MaxArt2501/object-observe#15]
One could always manually set it up to be a polyfill, but we cannot do the reverse.

Simply looking at a file that uses `objectObserve()`, a new or third-party developer will know that a non-native function is being used, even if it is only an interface to the native function (when it's available). In such cases, it still communicates the additional step in the algorithm, and the developer can choose to dig deeper to find out more.

**Comment by MaxArt2501** [comment]
This isn't going to happen. The current polyfill exposition will stay as it is.

If using a method named like `objectObserve` is preferred, the developer can just assign

``` js
// See object-observe.js
var objectObserve = Object.observe;
```

and eventually delete the `observe` property from `Object` if the function isn't native (which is also trivial to check).
