### ISSUE TITLE
Object.observe cannot be called on the global proxy object

### ISSUE THREAD

**Issue by MaxArt2501** [MaxArt2501/object-observe#19]
When trying to observe the `window` object (in a browser environment) or the `global` object (in Node), a `TypeError` should be thrown with the above message.

**Comment by bisubus** [comment]
That's interesting, because I have primarily considered Object.observe as alternative to Gecko-only Object.prototype.watch(). What is the reason behind that?

**Comment by MaxArt2501** [comment]
I can only guess it was for performance reasons.

**Comment by bisubus** [comment]
Yes, this makes sense, thanks.
