### ISSUE TITLE
root is undefined in FireFox

### ISSUE THREAD

**Issue by wangbagang** [MaxArt2501/object-observe#21]
when I used the js in FireFox 47, there have a error 'TypeError: root is undefined'

**Comment by MaxArt2501** [comment]
I'm not able to reproduce the issue. Can you provide more details?
What version are you using, and how are you including the package?
Does it work in other browsers?

**Comment by wangbagang** [comment]
@MaxArt2501 I am using the es6's "import" like `import './vendor/object-observe',` In chrome of the latest version have the error `object-observe.js:117 Uncaught TypeError: Cannot read property 'Map' of undefined` ,andl i am using the latest version of object-observe.js

**Comment by MaxArt2501** [comment]
Firefox doesn't support ES2015 modules. Are you transpiling your code? With Babel, maybe, and then passing everything through Browserify or Webpack? What's your development stack?

Anyway, the correct way to use `import` with this package is just this:

```
import "object.observe";
```

which gets compiled into

```
require("object.observe");
```

I recommend you to be more precise when reporting your issues.

**Comment by wangbagang** [comment]
I am sorry, I have used webpack and Balel to transform my code. 
And I was not used `npm install object.observe`, I just want to use the "object-observe.js" like a vendor
used npm install will be no problem
