### ISSUE TITLE
[Question] How do you minify this code?

### ISSUE THREAD

**Issue by abdulhannanali** [MaxArt2501/object-observe#23]
Hey @MaxArt2501 ,

Object.observe compatibility with older browsers is outstanding. I am doing some work that requires me to support older browsers as low as IE6. However, building with Webpack and minifying has been a disaster since it doesn't support older browers such as IE8. I would like to know what tool did you use at that time to minify or build (if any) this library. This would help me in writing more cross browser compliant code. Thanks a lot for help.  

Regards,
Hannan

**Comment by MaxArt2501** [comment]
I just use [uglify](https://github.com/mishoo/UglifyJS2).

**Comment by abdulhannanali** [comment]
Thanks @MaxArt2501 That was my initial guess too. Do you use any specific options?
