### ISSUE TITLE
Wrong bower version in tag 0.2.2

### ISSUE THREAD

**Issue by manolo** [MaxArt2501/object-observe#3]
The json file in tag 0.2.2 should match, but it is 0.1.1 causing a bower install error

https://github.com/MaxArt2501/object-observe/blob/v0.2.2/bower.json

**Comment by MaxArt2501** [comment]
You're correct. My bad, it slipped. I'll address this issue in the next release.
In the meanwhile, you should be able to install the package anyway, getting just a mismatch warning. Is it right?

**Comment by manolo** [comment]
For some reason our integration server refuses to install although in local it installs, we have changed to 0.2.1 and it installs and works in the meanwhile

**Comment by MaxArt2501** [comment]
The new release [0.2.3](https://github.com/MaxArt2501/object-observe/releases/tag/v0.2.3) should fix the issue.
Sorry for the inconvenience.
